version: 2

jobs:
  test:
    docker:
      - image: circleci/golang:1.14.0
    steps:
      - checkout
      - run: go mod download
      - run: go get -v -t -d ./...
      - run: go test -v ./...
  build:
    docker:
      - image: circleci/golang:1.14.0
    steps:
      - checkout
      - run: go build github.com/MarioCarrion/nit/testdata
      - run: go build github.com/MarioCarrion/nit/cmd/nit
  lint:
    docker:
      - image: circleci/golang:1.14.0
    steps:
      - checkout
      - run: go mod tidy
      - run: go install github.com/golangci/golangci-lint/cmd/golangci-lint
      - run: golangci-lint run ./...
      - run: go install github.com/MarioCarrion/nit/cmd/nit
      - run: nit -pkg github.com/MarioCarrion/nit github.com/MarioCarrion/nit github.com/MarioCarrion/nit/cmd/nit
  release:
    docker:
      - image: circleci/golang:1.14.0
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  test_and_lint:
    jobs:
      - test
      - build
      - lint
  release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
